spring:
  application:
    name: WarehouseManagement
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/management?useSSL=true&serverTimezone=UTC&characterEncoding=utf-8
    url: jdbc:mysql://192.168.0.129:3306/management?useSSL=true&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    encoding: UTF-8 # THYMELEAF
    cache: false    # 热部署静态文件
server:
#  servlet:
#    context-path: /app
  port: 8082